// Generated by scripts/build-studio-config.mjs — do not commit.
window.STUDIO_APP_CONFIG_LOCAL = {
  firebase: {
    url: "https://arh-firebase-db-default-rtdb.asia-southeast1.firebasedatabase.app",
    root: "studio",
  },
  auth: {
    apiKey: "AIzaSyD7PzpBG9fk3BGM96vYOyKDaaOe3FDFnnY",
  },
};
