// Generated by scripts/build-family-hub-config.mjs — do not commit.
window.FAMILY_HUB_CONFIG_LOCAL = {
  firebase: {
    url: "https://arh-firebase-db-default-rtdb.asia-southeast1.firebasedatabase.app",
    root: "familyHub",
    apiKey: "AIzaSyD7PzpBG9fk3BGM96vYOyKDaaOe3FDFnnY",
  },
};
