<#
.SYNOPSIS
  Renders apps/studio/studio.config.local.js from environment variables.

.DESCRIPTION
  Reads STUDIO_API_KEY (optional), STUDIO_DEV_PIN and STUDIO_DB_SECRET -
  either already exported in the shell, or from a dotenv file produced by:

      infisical export --env=dev --path=/arh-family-lab/studio --format=dotenv > .env.studio

  and writes studio.config.local.js next to this script's parent folder
  (apps/studio/). That file is gitignored; never commit it.

.EXAMPLE
  ./scripts/render-local-config.ps1 -EnvFile .env.studio

.EXAMPLE
  $env:STUDIO_DEV_PIN = "1234"; $env:STUDIO_DB_SECRET = "..."
  ./scripts/render-local-config.ps1
#>
param(
  [string]$EnvFile
)

$ErrorActionPreference = "Stop"
$studioDir = Split-Path -Parent $PSScriptRoot

# Load vars from the dotenv file without mutating the real environment.
$fileVars = @{}
if ($EnvFile) {
  if (-not (Test-Path $EnvFile)) { throw "Env file not found: $EnvFile" }
  foreach ($line in Get-Content $EnvFile) {
    $line = $line.Trim()
    if (-not $line -or $line.StartsWith("#")) { continue }
    $idx = $line.IndexOf("=")
    if ($idx -lt 1) { continue }
    $name = $line.Substring(0, $idx).Trim()
    $value = $line.Substring($idx + 1).Trim().Trim('"').Trim("'")
    $fileVars[$name] = $value
  }
}

function Get-StudioVar([string]$name) {
  if ($fileVars.ContainsKey($name) -and $fileVars[$name]) { return $fileVars[$name] }
  $envValue = [Environment]::GetEnvironmentVariable($name)
  if ($envValue) { return $envValue }
  return $null
}

$apiKey   = Get-StudioVar "STUDIO_API_KEY"
$devPin   = Get-StudioVar "STUDIO_DEV_PIN"
$dbSecret = Get-StudioVar "STUDIO_DB_SECRET"

if (-not $devPin)   { throw "STUDIO_DEV_PIN is missing (set it in the shell or in $EnvFile)." }
if (-not $dbSecret) { throw "STUDIO_DB_SECRET is missing (set it in the shell or in $EnvFile)." }

# Escape for embedding in a JS single-quoted string.
function ConvertTo-JsString([string]$s) {
  return $s.Replace("\", "\\").Replace("'", "\'").Replace("`n", "\n").Replace("`r", "")
}

$authSection = ""
if ($apiKey) {
  $authSection = @"
  auth: {
    apiKey: '$(ConvertTo-JsString $apiKey)',
  },

"@
}

$content = @"
/*
  GENERATED by scripts/render-local-config.ps1 - do not edit by hand.
  Gitignored local secret override for studio.config.js. Never commit.
*/
const STUDIO_APP_CONFIG_LOCAL = {
$authSection  dev: {
    pin: '$(ConvertTo-JsString $devPin)',
    dbSecret: '$(ConvertTo-JsString $dbSecret)',
  },
};
"@

$outPath = Join-Path $studioDir "studio.config.local.js"
Set-Content -Path $outPath -Value $content -Encoding UTF8
Write-Host "Wrote $outPath"
if (-not $apiKey) { Write-Host "Note: STUDIO_API_KEY not set - auth.apiKey stays as committed in studio.config.js." }
